/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lz.view;

import br.com.lz.dao.FabricanteDAO;
import br.com.lz.dao.ItensVendaDAO;
import br.com.lz.dao.ProdutosDAO;
import br.com.lz.domain.Fabricante;
import br.com.lz.domain.ItensVenda;
import br.com.lz.domain.Produtos;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class Venda extends javax.swing.JFrame {

    List<Produtos> lista = new ArrayList<>();
    List<ItensVenda> itv = new ArrayList<>();
    List<ItensVenda> itv2 = new ArrayList<>();
    
    public Venda() {
        initComponents();
        setLocationRelativeTo(null);
        atualizaTabelaProd();
        total.setVisible(false);
        atualizaTabelaProd();
        atualizaTabelaIt();
        atualizaTabelaServ();
        setResizable(false);
        somar();
   }
    
    private Produtos retornaObjeto() {
        Produtos produto = new Produtos();
        produto.setNome(txPesqProd.getText().toUpperCase()); 
        
        return produto;
    }
                                   
    private void atualizaTabelaProd(){

        try {
            lista = ProdutosDAO.pesquisar(retornaObjeto());
            DefaultTableModel modelo = (DefaultTableModel) tbProduto.getModel();
            modelo.setNumRows(0);
            
            for (Produtos prod: lista) {
                if(prod.getProdserv().equals("S")){
                   prod.setProdserv("Serviço");
                    modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        null,
                        prod.getProdserv()
                    
                });
                }else{
                    prod.setProdserv("Produto");
                    modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    
                });
                
                }
                
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void atualizaTabelaIt(){

        try {
            itv = ItensVendaDAO.listar();
            DefaultTableModel modelo = (DefaultTableModel) tbItv.getModel();
            modelo.setNumRows(0);
            
            for (ItensVenda it: itv) {
                modelo.addRow(new Object[]{
                    it.getProduto().getNome(),
                    it.getQuantidade(),
                    it.getValorParcial(),
                    it.getStatus()
                    
                });
                
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
    
    private void atualizaTabelaServ(){

        try {
            itv2 = ItensVendaDAO.listarServ();
            
            DefaultTableModel modelo = (DefaultTableModel) tbServ.getModel();
            modelo.setNumRows(0);
            
            for (ItensVenda it: itv2) {
                modelo.addRow(new Object[]{
                    it.getProduto().getNome(),
                    it.getQuantidade(),
                    it.getValorParcial()
                    
                });
                
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnFinalizar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        total = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        btnRemoveCesta = new javax.swing.JButton();
        btnNovo = new javax.swing.JButton();
        txPesqProd = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbItv = new javax.swing.JTable();
        btnRemoveCesta1 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbServ = new javax.swing.JTable();
        btnRemoveCesta3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        total1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda");
        setPreferredSize(new java.awt.Dimension(1154, 778));
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        btnFinalizar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnFinalizar.setForeground(new java.awt.Color(0, 51, 102));
        btnFinalizar.setText("Finalizar Venda");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lz/icones/money.png"))); // NOI18N
        jLabel1.setText("Valor Total:");

        total.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        total.setForeground(new java.awt.Color(255, 255, 255));
        total.setText("VALOR TOTAL");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(total)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(741, 741, 741)
                .addComponent(btnFinalizar)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(total)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        tbProduto.setBackground(new java.awt.Color(255, 255, 255));
        tbProduto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbProduto.setForeground(new java.awt.Color(0, 51, 102));
        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Produto/Serviço", "Preço", "Estoque", "Tipo"
            }
        ));
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduto);
        tbProduto.getAccessibleContext().setAccessibleDescription("");

        btnAdd.setForeground(new java.awt.Color(0, 51, 102));
        btnAdd.setText("Adicionar à cesta");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemoveCesta.setForeground(new java.awt.Color(0, 51, 102));
        btnRemoveCesta.setText("Remover Produto");
        btnRemoveCesta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCestaActionPerformed(evt);
            }
        });

        btnNovo.setForeground(new java.awt.Color(0, 51, 102));
        btnNovo.setText("Novo Produto");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        txPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPesqProdKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 51, 102));
        jLabel4.setText("Pesquise o nome do Produto/Serviço:");

        btnAdd1.setForeground(new java.awt.Color(0, 51, 102));
        btnAdd1.setText("Voltar");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        tbItv.setBackground(new java.awt.Color(255, 255, 255));
        tbItv.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbItv.setForeground(new java.awt.Color(0, 51, 102));
        tbItv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade ", "Valor Parcial"
            }
        ));
        tbItv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItvMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbItv);

        btnRemoveCesta1.setForeground(new java.awt.Color(0, 51, 102));
        btnRemoveCesta1.setText("Novo Serviço");
        btnRemoveCesta1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCesta1ActionPerformed(evt);
            }
        });

        tbServ.setBackground(new java.awt.Color(255, 255, 255));
        tbServ.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        tbServ.setForeground(new java.awt.Color(0, 51, 102));
        tbServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Serviço", "Quantidade ", "Valor parcial"
            }
        ));
        tbServ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbServMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbServ);

        btnRemoveCesta3.setForeground(new java.awt.Color(0, 51, 102));
        btnRemoveCesta3.setText("Remover Serviço");
        btnRemoveCesta3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveCesta3ActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 51, 102));
        jPanel3.setForeground(new java.awt.Color(0, 51, 102));

        total1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        total1.setForeground(new java.awt.Color(255, 255, 255));
        total1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lz/icones/cart__.png"))); // NOI18N
        total1.setText("Cesta");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(total1)
                .addGap(523, 523, 523))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(total1)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNovo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveCesta1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRemoveCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAdd1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRemoveCesta3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(4, 4, 4)))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 21, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnRemoveCesta1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemoveCesta3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRemoveCesta, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txPesqProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesqProdKeyTyped
        atualizaTabelaProd();
        
    }//GEN-LAST:event_txPesqProdKeyTyped

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        Produtos p = lista.get(tbProduto.getSelectedRow());
        ItensVenda it= new ItensVenda();
        int idProd= p.getId();
        it.setProduto(p);
        it.setQuantidade(1);
        it.setValorParcial(p.getPreco());
        
        List<ItensVenda> itv = new ArrayList<>();
        int qt= 0;
        
        try {
            
            if(p.getProdserv().equals("Serviço")){
                 if(ItensVendaDAO.validaExist(it.getProduto().getId())){
                     ItensVendaDAO.alteraQt(it);
                
                    itv= ItensVendaDAO.listarProd(it.getProduto().getId());

                    for(ItensVenda i: itv){
                        qt= i.getQuantidade();
                        ItensVendaDAO.alteraValor(i, qt, idProd);             
                    }

                    atualizaTabelaServ();
                    somar();
                 }else{
                     ItensVendaDAO.inserir(it);
                     atualizaTabelaServ();
                    somar();
                 }
            atualizaTabelaServ();
            }else if(p.getEstoque() > 0){
                    if(ItensVendaDAO.validaExist(it.getProduto().getId())){
                        ItensVendaDAO.alteraQt(it);
                        ProdutosDAO.removeEstoque(p);

                        itv= ItensVendaDAO.listarProd(it.getProduto().getId());
                        for(ItensVenda i: itv){
                            qt= i.getQuantidade();
                            ItensVendaDAO.alteraValor(i, qt, idProd);             
                        }
                        somar();

                    }else{
                        ItensVendaDAO.inserir(it);
                        ProdutosDAO.removeEstoque(p);
                        somar();
                    }            

                atualizaTabelaProd();   
                atualizaTabelaIt();
                
            }else if(p.getEstoque() <= 0){
                JOptionPane.showMessageDialog(null, "Não foi possível adicionar, produto não se"
                        + " encontra em estoque.");
            }
       } catch (SQLException ex) {
           JOptionPane.showMessageDialog(null, "Erro ao adicionar");
           ex.printStackTrace();
        }catch(ArrayIndexOutOfBoundsException ex){
            JOptionPane.showMessageDialog(null, "Por favor, selecione uma coluna da tabela primeiro.");
        } 
       
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnAdd1ActionPerformed

    public Double somar(){
        Double valor;
        Double soma= 0.0;
        
        List<Double> somas = new ArrayList<>();
        
        try {
            itv= ItensVendaDAO.listar();
            itv2 = ItensVendaDAO.listarServ();
            
            for(ItensVenda i: itv2){
                valor= i.getValorParcial();
               somas.add(valor);
            }

            for(ItensVenda i: itv){
                valor= i.getValorParcial();
                somas.add(valor);
            }

            System.out.println(somas);
            
            for(Double sum: somas){
                soma+= sum;
            }
            
            
            
            
            total.setVisible(true);
            total.setText(""+soma+"");
            
            
        } catch (SQLException ex) {
            
        }
        
        return soma;
    }
    
    public Double subtrair(ItensVenda i){
       Double val= 0.0;
       
       val= i.getValorParcial()-i.getProduto().getPreco();
       
       return val;
    }
    
    public Double subtrairServ(ItensVenda i){
       Double val= 0.0;
       Double aux;
       aux= i.getValorParcial() / i.getQuantidade();
       System.out.println(aux);
       val= i.getValorParcial() - aux;
               
       
       return val;
    }
    
    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        atualizaTabelaIt();
        atualizaTabelaProd();
        somar();
        atualizaTabelaServ();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        CadastroProdutos c= new CadastroProdutos();
        c.setVisible(true);
                
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnRemoveCestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCestaActionPerformed
        
        ItensVenda it= itv.get(tbItv.getSelectedRow());
        System.out.println(evt.getWhen());
        Double val= 0.0;
        val= subtrair(it);
        
        int qt= it.getQuantidade();
        if(qt != 1){
            try {
                    
                atualizaTabelaIt();
                ItensVendaDAO.alteraQuantidade(it);
                
                ItensVendaDAO.subtrai(val, it);
                
                ProdutosDAO.addEstoque(it);
                atualizaTabelaIt();
                atualizaTabelaProd();
                somar();
            } catch (SQLException ex) {
                
            }
                
        }else{
            int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o item: "+ it.getProduto().getNome()+" da cesta?");
              if(opc == JOptionPane.YES_OPTION){
                  try{
                      ProdutosDAO.addEstoque(it);
                      ItensVendaDAO.excluir(it);
                      
                      atualizaTabelaIt();

                  }catch(MySQLIntegrityConstraintViolationException ex){
                      JOptionPane.showMessageDialog(null, "Não pode excluir");
                  } catch (SQLException ex) {
                      JOptionPane.showMessageDialog(null, "Não pode excluir");
                  }catch(ArrayIndexOutOfBoundsException ex){
                      JOptionPane.showMessageDialog(null, "Por favor, selecione uma coluna da tabela primeiro.");
                  } 

              }
        }
        
    }//GEN-LAST:event_btnRemoveCestaActionPerformed

    private void tbItvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItvMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbItvMouseClicked

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        if(total.getText().equals("0.0")){
            JOptionPane.showMessageDialog(null, "Não é possivel finalizar uma venda com valor vazio!");
        }else{
            FinalizaVenda f= new FinalizaVenda(total.getText());
            f.setVisible(true);
        }
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnRemoveCesta1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCesta1ActionPerformed
        CadastroServicos c= new CadastroServicos();
        c.setVisible(true);
    }//GEN-LAST:event_btnRemoveCesta1ActionPerformed

    private void tbServMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbServMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbServMouseClicked

    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked

    }//GEN-LAST:event_tbProdutoMouseClicked

    private void btnRemoveCesta3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveCesta3ActionPerformed
        ItensVenda it= itv2.get(tbServ.getSelectedRow());
        
        Double val= 0.0;
        val= subtrairServ(it);
        
        int qt= it.getQuantidade();
        if(qt != 1){
            try {
                    
                atualizaTabelaIt();
                ItensVendaDAO.alteraQuantidade(it);
                
               ItensVendaDAO.subtraiServ(val, it);
                
               atualizaTabelaServ();
                atualizaTabelaProd();
                somar();
            } catch (SQLException ex) {
                
            }
                
        }else{
            int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o serviço: "+ it.getProduto().getNome()+" da cesta?");
              if(opc == JOptionPane.YES_OPTION){
                  try{
                      ItensVendaDAO.excluir(it);
                      
                      atualizaTabelaIt();

                  }catch(MySQLIntegrityConstraintViolationException ex){
                      JOptionPane.showMessageDialog(null, "Não pode excluir");
                  } catch (SQLException ex) {
                      JOptionPane.showMessageDialog(null, "Não pode excluir");
                  }catch(ArrayIndexOutOfBoundsException ex){
                      JOptionPane.showMessageDialog(null, "Por favor, selecione uma coluna da tabela primeiro.");
                  } 

              }
        }
    }//GEN-LAST:event_btnRemoveCesta3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Venda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnRemoveCesta;
    private javax.swing.JButton btnRemoveCesta1;
    private javax.swing.JButton btnRemoveCesta3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbItv;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTable tbServ;
    private javax.swing.JLabel total;
    private javax.swing.JLabel total1;
    private javax.swing.JTextField txPesqProd;
    // End of variables declaration//GEN-END:variables
}
