/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lz.view;

import br.com.lz.dao.ProdutosDAO;
import br.com.lz.domain.Produtos;
import com.mysql.jdbc.exceptions.MySQLIntegrityConstraintViolationException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author felip
 */
public class VisualizaProdutos extends javax.swing.JFrame {

    List<Produtos> lista = new ArrayList<>();
    
    public VisualizaProdutos() {
        initComponents();
        btnExc.setEnabled(false);
        btnALT.setEnabled(false);
        setLocationRelativeTo(null);
        atualizaTabela();
        setResizable(false);
        ambos.setSelected(true);
    }
    
    private Produtos retornaObjeto() {
        Produtos produto = new Produtos();
        produto.setNome(txPesqProd.getText().toUpperCase()); 
        
        return produto;
    }
                                   
    private void atualizaTabela(){

        try {
            lista = ProdutosDAO.pesquisar(retornaObjeto());
            DefaultTableModel modelo = (DefaultTableModel) tbProduto.getModel();
            modelo.setNumRows(0);
            
            for (Produtos prod: lista) {
                if(prod.getProdserv().equals("S")){
                    prod.setProdserv("Serviço");
                     modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    });
                }else{
                    prod.setProdserv("Produto");
                    modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    
                    });
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } 

     private void atualizaTabelaProd(){

        try {
            lista = ProdutosDAO.listaProd(retornaObjeto());
            DefaultTableModel modelo = (DefaultTableModel) tbProduto.getModel();
            modelo.setNumRows(0);
            
            for (Produtos prod: lista) {
                if(prod.getProdserv().equals("S")){
                    prod.setProdserv("Serviço");
                     modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    });
                }else{
                    prod.setProdserv("Produto");
                    modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    
                    });
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } 
     
     private void atualizaTabelaServ(){

        try {
            lista = ProdutosDAO.listaServ(retornaObjeto());
            DefaultTableModel modelo = (DefaultTableModel) tbProduto.getModel();
            modelo.setNumRows(0);
            
            for (Produtos prod: lista) {
                if(prod.getProdserv().equals("S")){
                    prod.setProdserv("Serviço");
                     modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    });
                }else{
                    prod.setProdserv("Produto");
                    modelo.addRow(new Object[]{
                        prod.getId(),
                        prod.getNome(),
                        prod.getPreco(),
                        prod.getEstoque(),
                        prod.getProdserv()
                    
                    });
                }
            }

        } catch (SQLException e) {
            e.printStackTrace();
        }
    } 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txPesqProd = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnExc = new javax.swing.JButton();
        btnALT = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        ambos = new javax.swing.JRadioButton();
        btnAdd1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos");
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo ", "Nome ", "Preço", "Estoque", "Tipo"
            }
        ));
        tbProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbProdutoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbProduto);

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setText("Descrição:");

        txPesqProd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txPesqProdKeyTyped(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 51, 102));
        btnAdd.setText("+ Produto");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnExc.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnExc.setForeground(new java.awt.Color(0, 51, 102));
        btnExc.setText("Excluir");
        btnExc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcActionPerformed(evt);
            }
        });

        btnALT.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnALT.setForeground(new java.awt.Color(0, 51, 102));
        btnALT.setText("Alterar");
        btnALT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnALTActionPerformed(evt);
            }
        });

        btnVoltar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnVoltar.setForeground(new java.awt.Color(0, 51, 102));
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Produtos");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Serviços");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        buttonGroup1.add(ambos);
        ambos.setText("Ambos");
        ambos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ambosActionPerformed(evt);
            }
        });

        btnAdd1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAdd1.setForeground(new java.awt.Color(0, 51, 102));
        btnAdd1.setText("+ Serviço");
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(txPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(83, 83, 83)
                        .addComponent(jRadioButton1)
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButton2)
                        .addGap(29, 29, 29)
                        .addComponent(ambos))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 709, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnALT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txPesqProd, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(ambos))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAdd1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnExc, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnALT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(159, 159, 159)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        CadastroProdutos c= new CadastroProdutos();
        c.setVisible(true);
                
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnExcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcActionPerformed
        Produtos p= lista.get(tbProduto.getSelectedRow());

        int opc = JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o Produto: "+ p.getNome()+"?");

        if(opc == JOptionPane.YES_OPTION){
            try{
                ProdutosDAO.excluir(p);
                atualizaTabela();

            }catch(MySQLIntegrityConstraintViolationException ex){
                JOptionPane.showMessageDialog(null, "Não pode excluir");
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Não pode excluir, verifique se produto já está \nvinculado à uma venda");
            }

        }
    }//GEN-LAST:event_btnExcActionPerformed

    private void btnALTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnALTActionPerformed
        Produtos p= lista.get(tbProduto.getSelectedRow());
        
        if(p.getProdserv().equals("Serviço")){
            CadastroServicos cad= new CadastroServicos(p);
            cad.setVisible(true);

            btnExc.setEnabled(false);
            btnALT.setEnabled(false);
        }else{
            CadastroProdutos cad= new CadastroProdutos(p);
            cad.setVisible(true);

            btnExc.setEnabled(false);
            btnALT.setEnabled(false);
        }
        
        
 
    }//GEN-LAST:event_btnALTActionPerformed

    private void txPesqProdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txPesqProdKeyTyped
        atualizaTabela();
    }//GEN-LAST:event_txPesqProdKeyTyped

    private void tbProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbProdutoMouseClicked
        btnALT.setEnabled(true);
        btnExc.setEnabled(true);
    }//GEN-LAST:event_tbProdutoMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        atualizaTabela();
    }//GEN-LAST:event_formWindowGainedFocus

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        atualizaTabelaProd();
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        atualizaTabelaServ();
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void ambosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ambosActionPerformed
        atualizaTabela();
    }//GEN-LAST:event_ambosActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
        new CadastroServicos().setVisible(true);
    }//GEN-LAST:event_btnAdd1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizaProdutos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizaProdutos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton ambos;
    private javax.swing.JButton btnALT;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnExc;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTextField txPesqProd;
    // End of variables declaration//GEN-END:variables
}
